version: "3"
services:

  spark-master:
    image: dxxpteam/xpspark:2.3p3.6.4
    hostname: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    environment:
      TZ: Europe/Brussels
    ports:
      - ${INSTANCE_ID}081:8080
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G

  spark-worker:
    image: dxxpteam/xpspark:2.3p3.6.4
    hostname: spark-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 8
      SPARK_WORKER_MEMORY: 20g
      PYTHONPATH: /mnt/data/shared/lib
      TZ: Europe/Brussels
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 20g
        reservations:
          memory: 20g
    volumes:
      - /mnt/data:/mnt/data

  zeppelin:
    image: dxxpteam/xpzeppelin:0.8-2.3p3.6.4
    hostname: zeppelin
    ports :
      - "${INSTANCE_ID}080:8080"
      - "${INSTANCE_ID}000:5000"
    environment:
      - SPARK_HOME=/opt/spark
      - MASTER=spark://spark-master:7077
      - ZEPPELIN_JAVA_OPTS=-Dspark.executor.memory=20g
      - ZEPPELIN_NOTEBOOK_DIR=/opt/NotebookRepo
      - HTTP_PROXY=http://proxy.lbs.alcatel-lucent.com:8000
      - HTTPS_PROXY=http://proxy.lbs.alcatel-lucent.com:8000
      - http_proxy=http://proxy.lbs.alcatel-lucent.com:8000
      - https_proxy=http://proxy.lbs.alcatel-lucent.com:8000
      - PYTHONPATH=/mnt/data/shared/lib:/
      - TZ=Europe/Brussels
      - ZEPPELIN_MEM=-Xmx2048m -XX:MaxPermSize=1024m
      - MLFLOW_TRACKING_URI=file:/opt/zeppelin/logs/mlruns
    command: bin/zeppelin.sh;mlflow ui --host 0.0.0.0 --file-store ./logs/mlruns
    volumes:
      - /mnt/data:/mnt/data
      - /mnt/NotebookRepo:/opt/NotebookRepo
      - /mnt/zeppelinConfig/shiro.ini:/opt/zeppelin/conf/shiro.ini
      - /mnt/zeppelinConfig/notebook-authorization.json:/opt/zeppelin/conf/notebook-authorization.json
      - /mnt/data/shared/mlruns/instance_id/${INSTANCE_ID}:/opt/zeppelin/logs/mlruns
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
      placement:
        constraints: [node.hostname == slave-${INSTANCE_ID}]
